#!/usr/bin/env python3
import os

LT = chr(60)
GT = chr(62)

def L(s):
    return LT + s + GT

def build():
    chunks = []
    
    # Header
    chunks.append('import { randomUUID } from "node:crypto";')
    chunks.append('')
    chunks.append('interface SearchResult {')
    chunks.append('  title: string;')
    chunks.append('  url: string;')
    chunks.append('  snippet?: string;')
    chunks.append('}')
    chunks.append('')
    
    chunks.append('export interface WebSearchArgs {')
    chunks.append('  query: string;')
    chunks.append('  engine?: "duckduckgo" | "brave" | "auto";')
    chunks.append('  maxResults?: number;')
    chunks.append('  scrapePages?: number;')
    chunks.append('}')
    chunks.append('')
    
    chunks.append('export interface WebSearchResult {')
    chunks.append('  query: string;')
    chunks.append('  engine: "mimo" | "serper" | "duckduckgo";')
    chunks.append('  searchedAt: string;')
    chunks.append('  requestedPages: number;')
    chunks.append('  scrapedPages: number;')
    chunks.append(f'  results: {L("Array")}{L("{")}')
    chunks.append('    title: string;')
    chunks.append('    url: string;')
    chunks.append('    snippet?: string;')
    chunks.append('    scraped: boolean;')
    chunks.append('    summary?: string;')
    chunks.append('    error?: string;')
    chunks.append(f'  {GT};')
    chunks.append('  synthesis: {')
    chunks.append('    summary: string;')
    chunks.append('    solutionCandidates: string[];')
    chunks.append('    recommendedOrder: string[];')
    chunks.append('  };')
    chunks.append('}')
    chunks.append('')
    
    # Main function
    chunks.append(f'export async function webSearchTool(')
    chunks.append(f'  args: WebSearchArgs,')
    chunks.append(f'  options: {{ fetchImpl?: any; now?: Date }} = {{}},')
    chunks.append(f'): Promise{L("WebSearchResult")} {{')
    chunks.append(f'  const fetchImpl = options.fetchImpl ?? (fetch as any);')
    chunks.append(f'  const query = args.query;')
    chunks.append(f'  const maxResults = args.maxResults ?? 10;')
    chunks.append(f'')
    chunks.append(f'  // Run 3 search engines in PARALLEL')
    chunks.append(f'  const [mimoResults, serperResults, ddgResults] = await Promise.all([')
    chunks.append(f'    searchMiMo(query, maxResults, fetchImpl),')
    chunks.append(f'    searchSerper(query, maxResults, fetchImpl),')
    chunks.append(f'    searchDuckDuckGo(query, maxResults, fetchImpl),')
    chunks.append(f'  ]);')
    chunks.append(f'')
    chunks.append(f'  // Merge and deduplicate')
    chunks.append(f'  const allResults = dedupeByUrl([...mimoResults, ...serperResults, ...ddgResults]).slice(0, maxResults);')
    chunks.append(f'')
    chunks.append(f'  // Scrape pages for content')
    chunks.append(f'  const scraped = await Promise.all(')
    chunks.append(f'    allResults.slice(0, Math.min(maxResults, 10)).map(async (result) => {{')
    chunks.append(f'      try {{')
    chunks.append(f'        const html = await fetchText(result.url, fetchImpl, 15_000);')
    chunks.append(f'        return {{ ...result, scraped: true, summary: summarizePage(extractReadableText(html), query) }};')
    chunks.append(f'      }} catch (error) {{')
    chunks.append(f'        return {{ ...result, scraped: false, error: error instanceof Error ? error.message : String(error) }};')
    chunks.append(f'      }}')
    chunks.append(f'    }}),')
    chunks.append(f'  );')
    chunks.append(f'')
    chunks.append(f'  const synthesis = synthesizeResearch(query, scraped);')
    chunks.append(f'')
    chunks.append(f'  return {{')
    chunks.append(f'    query,')
    chunks.append(f'    engine: "mimo",')
    chunks.append(f'    searchedAt: new Date().toISOString(),')
    chunks.append(f'    requestedPages: maxResults,')
    chunks.append(f'    scrapedPages: scraped.filter((s) => s.scraped).length,')
    chunks.append(f'    results: scraped,')
    chunks.append(f'    synthesis,')
    chunks.append(f'  }};')
    chunks.append(f'}}')
    chunks.append(f'')

    # searchMiMo
    chunks.append(f'async function searchMiMo(query: string, maxResults: number, fetchImpl: any): Promise{L("SearchResult[]")} {{')
    chunks.append(f'  const apiKey = process.env.MIMO_SEARCH_API_KEY || "";')
    chunks.append(f'  if (!apiKey) return [];')
    chunks.append(f'  try {{')
    chunks.append(f'    const response = await fetchWithTimeout("https://api.xiaomimimo.com/v1/chat/completions", fetchImpl, 20_000, {{')
    chunks.append(f'      method: "POST",')
    chunks.append(f'      headers: {{ "api-key": apiKey, "Content-Type": "application/json" }},')
    chunks.append(f'      body: JSON.stringify({{')
    chunks.append(f'        model: "mimo-v2.5-pro",')
    chunks.append(f'        messages: [{{ role: "user", content: query }}],')
    chunks.append(f'        tools: [{{ type: "web_search", max_keyword: 5, force_search: true, limit: maxResults }}],')
    chunks.append(f'        max_completion_tokens: 2048,')
    chunks.append(f'        temperature: 1.0, top_p: 0.95, stream: false,')
    chunks.append(f'        thinking: {{ type: "disabled" }},')
    chunks.append(f'      }}),')
    chunks.append(f'    }});')
    chunks.append(f'    if (!response.ok) return [];')
    chunks.append(f'    const data = await response.json() as any;')
    chunks.append(f'    const message = data.choices?.[0]?.message;')
    chunks.append(f'    const results: SearchResult[] = [];')
    chunks.append(f'    if (Array.isArray(message?.annotations)) {{')
    chunks.append(f'      for (const ann of message.annotations) {{')
    chunks.append(f'        if (ann.type === "url_citation" && ann.url) {{')
    chunks.append(f'          results.push({{ title: ann.title || ann.url, url: ann.url, snippet: ann.summary || "" }});')
    chunks.append(f'        }}')
    chunks.append(f'      }}')
    chunks.append(f'    }}')
    chunks.append(f'    return dedupeByUrl(results).slice(0, maxResults);')
    chunks.append(f'  }} catch {{')
    chunks.append(f'    return [];')
    chunks.append(f'  }}')
    chunks.append(f'}}')
    chunks.append(f'')

    # searchSerper
    chunks.append(f'async function searchSerper(query: string, maxResults: number, fetchImpl: any): Promise{L("SearchResult[]")} {{')
    chunks.append(f'  const apiKey = process.env.SERPER_SEARCH_API_KEY || "";')
    chunks.append(f'  if (!apiKey) return [];')
    chunks.append(f'  try {{')
    chunks.append(f'    const response = await fetchWithTimeout("https://google.serper.dev/search", fetchImpl, 10_000, {{')
    chunks.append(f'      method: "POST",')
    chunks.append(f'      headers: {{ "X-API-KEY": apiKey, "Content-Type": "application/json" }},')
    chunks.append(f'      body: JSON.stringify({{ q: query, num: maxResults }}),')
    chunks.append(f'    }});')
    chunks.append(f'    if (!response.ok) return [];')
    chunks.append(f'    const data = await response.json() as any;')
    chunks.append(f'    const results: SearchResult[] = [];')
    chunks.append(f'    const organic = data.organic || [];')
    chunks.append(f'    for (const item of organic) {{')
    chunks.append(f'      if (item.link && item.title) {{')
    chunks.append(f'        results.push({{ title: item.title, url: item.link, snippet: item.snippet || "" }});')
    chunks.append(f'      }}')
    chunks.append(f'    }}')
    chunks.append(f'    return results.slice(0, maxResults);')
    chunks.append(f'  }} catch {{')
    chunks.append(f'    return [];')
    chunks.append(f'  }}')
    chunks.append(f'}}')
    chunks.append(f'')

    # searchDuckDuckGo
    chunks.append(f'async function searchDuckDuckGo(query: string, maxResults: number, fetchImpl: any): Promise{L("SearchResult[]")} {{')
    chunks.append(f'  try {{')
    chunks.append(f'    const response = await fetchWithTimeout("https://html.duckduckgo.com/html/", fetchImpl, 10_000, {{')
    chunks.append(f'      method: "POST",')
    chunks.append(f'      headers: {{')
    chunks.append(f'        "Content-Type": "application/x-www-form-urlencoded",')
    chunks.append(f'        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36",')
    chunks.append(f'      }},')
    chunks.append(f'      body: "q=" + encodeURIComponent(query),')
    chunks.append(f'    }});')
    chunks.append(f'    if (!response.ok) return [];')
    chunks.append(f'    return parseDDGResults(await response.text(), maxResults);')
    chunks.append(f'  }} catch {{')
    chunks.append(f'    return [];')
    chunks.append(f'  }}')
    chunks.append(f'}}')
    chunks.append(f'')

    # parseDDGResults
    chunks.append(f'function parseDDGResults(html: string, maxResults: number): SearchResult[] {{')
    chunks.append(f'  const results: SearchResult[] = [];')
    chunks.append(f'  const blocks = html.match(/uddg=([^&"]+)/g) || [];')
    chunks.append(f'  for (let i = 0; i {LT} blocks.length && results.length {LT} maxResults; i++) {{')
    chunks.append(f'    try {{')
    chunks.append(f'      const url = decodeURIComponent(blocks[i].replace("uddg=", ""));')
    chunks.append(f'      if (url.startsWith("http")) {{')
    chunks.append(f'        results.push({{ title: url.split("/").pop() || url, url, snippet: "" }});')
    chunks.append(f'      }}')
    chunks.append(f'    }} catch {{}}')
    chunks.append(f'  }}')
    chunks.append(f'  return results;')
    chunks.append(f'}}')
    chunks.append(f'')

    # dedupeByUrl
    chunks.append(f'function dedupeByUrl(results: SearchResult[]): SearchResult[] {{')
    chunks.append(f'  const seen = new Set{L("string")}();')
    chunks.append(f'  return results.filter((r) => {{')
    chunks.append(f'    const key = r.url.toLowerCase();')
    chunks.append(f'    if (seen.has(key)) return false;')
    chunks.append(f'    seen.add(key);')
    chunks.append(f'    return true;')
    chunks.append(f'  }});')
    chunks.append(f'}}')
    chunks.append(f'')

    # fetchText
    chunks.append(f'async function fetchText(url: string, fetchImpl: any, timeoutMs: number): Promise{L("string")} {{')
    chunks.append(f'  const controller = new AbortController();')
    chunks.append(f'  const timeout = setTimeout(() => controller.abort(), timeoutMs);')
    chunks.append(f'  try {{')
    chunks.append(f'    const response = await fetchImpl(url, {{')
    chunks.append(f'      signal: controller.signal,')
    chunks.append(f'      headers: {{')
    chunks.append(f'        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36",')
    chunks.append(f'      }},')
    chunks.append(f'    }});')
    chunks.append(f'    return await response.text();')
    chunks.append(f'  }} finally {{')
    chunks.append(f'    clearTimeout(timeout);')
    chunks.append(f'  }}')
    chunks.append(f'}}')
    chunks.append(f'')

    # fetchWithTimeout
    chunks.append(f'async function fetchWithTimeout(url: string, fetchImpl: any, timeoutMs: number, init: any): Promise{L("any")} {{')
    chunks.append(f'  const controller = new AbortController();')
    chunks.append(f'  const timeout = setTimeout(() => controller.abort(), timeoutMs);')
    chunks.append(f'  try {{')
    chunks.append(f'    return await fetchImpl(url, {{ ...init, signal: controller.signal }});')
    chunks.append(f'  }} finally {{')
    chunks.append(f'    clearTimeout(timeout);')
    chunks.append(f'  }}')
    chunks.append(f'}}')
    chunks.append(f'')

    # extractReadableText
    chunks.append(f'function extractReadableText(html: string): string {{')
    chunks.append(f'  return html')
    chunks.append(f'    .replace(/[scriptstyle][^>]*>.*?\\\\/\\\\1/gi, " ")')
    chunks.append(f'    .replace(/{L("[^>]+")}{GT}/g, " ")')
    chunks.append(f'    .replace(/\\\\s+/g, " ").trim();')
    chunks.append(f'}}')
    chunks.append(f'')

    # summarizePage - CONTEXT SAFE (max 300 chars)
    chunks.append(f'function summarizePage(text: string, query: string): string {{')
    chunks.append(f'  const terms = query.toLowerCase().split(/[^a-z0-9_./-]+/).filter(t => t.length {GT} 2);')
    chunks.append(f'  const sentences = text.split(/(?=[.?!]\\\\s)/).filter(Boolean);')
    chunks.append(f'  const scored = sentences')
    chunks.append(f'    .map((s, i) => ({{ sentence: s, index: i, score: terms.reduce((sc, t) => sc + (s.toLowerCase().includes(t) ? 1 : 0), 0) }}))')
    chunks.append(f'    .sort((a, b) => b.score - a.score || a.index - b.index)')
    chunks.append(f'    .slice(0, 2)')
    chunks.append(f'    .sort((a, b) => a.index - b.index)')
    chunks.append(f'    .map(item => item.sentence);')
    chunks.append(f'  return (scored.length {GT} 0 ? scored : sentences.slice(0, 1)).join(" ").slice(0, 300);')
    chunks.append(f'}}')
    chunks.append(f'')

    # synthesizeResearch - CONTEXT SAFE (small output)
    chunks.append(f'function synthesizeResearch(query: string, results: any[]): {{ summary: string; solutionCandidates: string[]; recommendedOrder: string[]; }} {{')
    chunks.append(f'  const candidates: Set{L("string")} = new Set();')
    chunks.append(f'  const allText = results.filter(r => r.scraped).map(r => (r.summary || r.snippet || "")).join(" ").toLowerCase();')
    chunks.append(f'')
    chunks.append(f'  if (/jest|typescript|test|beforeall|expect/.test(allText)) candidates.add("Check test config: ts-jest/jest compatibility, @types/jest");')
    chunks.append(f'  if (/sqlite|glibc|native|better-sqlite3/.test(allText)) candidates.add("Use better-sqlite3 or sql.js (pure JS) for DB");')
    chunks.append(f'  if (/express|ws|websocket/.test(allText)) candidates.add("WebSocket: use ws library with express http.Server");')
    chunks.append(f'  if (/vite|react-scripts|webpack/.test(allText)) candidates.add("Build: downgrade Vite to v5 or use tsx");')
    chunks.append(f'  if (/docker|container/.test(allText)) candidates.add("Docker not available, use direct commands");')
    chunks.append(f'  if (/bcrypt|auth|cors/.test(allText)) candidates.add("Auth: use bcryptjs, cors middleware");')
    chunks.append(f'  if (candidates.size === 0) candidates.add("Apply smallest fix matching the error, then retry");')
    chunks.append(f'')
    chunks.append(f'  const arr = [...candidates] as string[];')
    chunks.append(f'  return {{')
    chunks.append(f'    summary: `Found ${{results.length}} results, scraped ${{results.filter(r => r.scraped).length}}. ${{arr[0] || "No patterns detected"}}`,')
    chunks.append(f'    solutionCandidates: arr,')
    chunks.append(f'    recommendedOrder: arr,')
    chunks.append(f'  }};')
    chunks.append(f'}}')
    chunks.append(f'')

    result = '\n'.join(chunks)
    target = 'src/tools/read/web-search.ts'
    with open(target, 'w') as f:
        f.write(result)
    print(f"Written {len(result)} bytes to {target}")

if __name__ == '__main__':
    build()
