/**
 * SkillManifest — declarative on-disk contract for a skill.
 *
 * The existing `ReaperSkill` (src/adaptive/types.ts) is the *runtime*
 * shape produced by parsing a `SKILL.md`. The new `SkillManifest` is
 * the *folder-level* shape produced by parsing `skill.json` next to
 * the SKILL.md. The two complement each other; the new SkillRegistry
 * merges them.
 *
 * Trust values are an extension of the existing `SkillScope`:
 *   - "builtin"              shipped under src/skills/built-in
 *   - "user-trusted"         installed under ~/.reaper/skills
 *   - "project-untrusted"    installed under <workspace>/.reaper/skills
 *                            (default; promoted via `skill trust`)
 *   - "extension-inherited"  lives inside an extension's skills/ folder;
 *                            inherits the parent extension's trust
 *   - "draft"                generated by `skill create` or
 *                            `SkillAuthor.createSkillFromRunTrace`;
 *                            cannot be activated until promoted
 *
 * Categories are exactly the 17 built-in skill names defined in the
 * Skills/Extensions plan. The validator rejects unknown categories.
 */

export type SkillTrust =
  | "builtin"
  | "user-trusted"
  | "project-untrusted"
  | "extension-inherited"
  | "draft";

export type SkillCategory =
  | "repo-understanding"
  | "bug-fixing"
  | "test-failure-debugging"
  | "typescript-refactor"
  | "python-debugging"
  | "frontend-react-debugging"
  | "api-backend-debugging"
  | "security-review"
  | "performance-review"
  | "documentation-writing"
  | "terminal-bench-solving"
  | "swe-bench-solving"
  | "agent-runtime-debugging"
  | "session-persistence"
  | "prompt-enhancement";

export const ALL_SKILL_CATEGORIES: readonly SkillCategory[] = [
  "repo-understanding",
  "bug-fixing",
  "test-failure-debugging",
  "typescript-refactor",
  "python-debugging",
  "frontend-react-debugging",
  "api-backend-debugging",
  "security-review",
  "performance-review",
  "documentation-writing",
  "terminal-bench-solving",
  "swe-bench-solving",
  "agent-runtime-debugging",
  "session-persistence",
  "prompt-enhancement",
];

export interface SkillValidationCommand {
  id: string;
  command: string;
  cwd?: string;
}

export interface SkillMemoryPolicy {
  mayReadProjectMemory: boolean;
  mayWriteProjectMemory: boolean;
  mayReadUserMemory: boolean;
  mayWriteUserMemory: boolean;
}

export interface SkillArgumentSpec {
  name: string;
  description: string;
  required?: boolean;
}

export interface SkillManifest {
  /** kebab-case; regex ^[a-z][a-z0-9-]{0,63}$ */
  name: string;
  /** semver (major.minor.patch) */
  version: string;
  /** One-line summary; the router uses this verbatim. */
  description: string;
  category: SkillCategory;
  /** Free-text "when to use" line; the router uses this for matching. */
  whenToUse: string;
  /** Keyword triggers for the SkillRouter. */
  triggers?: string[];
  /** Path globs for activateConditionalSkillsForPaths. */
  pathPatterns?: string[];
  /** Tools the model may call while this skill is active. */
  allowedTools: string[];
  /** Declared positional arguments; surfaced in `skill show`. */
  arguments?: SkillArgumentSpec[];
  /** Optional auxiliary folders relative to the skill root. */
  examples?: string[];
  templates?: string[];
  tests?: string[];
  resources?: string[];
  /** Validation commands; `skill test` runs them in declaration order. */
  validation?: { commands: SkillValidationCommand[] };
  /** Memory policy. Defaults to project-RW, user-R-none. */
  memoryPolicy?: SkillMemoryPolicy;
  /** Trust as declared on disk. Resolved at install time by TrustResolver. */
  trust: SkillTrust;
  author?: string;
  license?: string;
  /** Minimum Reaper version (semver) required to install/use. */
  minimumReaperVersion?: string;
}

/**
 * Summary returned by SkillRouter. Deliberately has no `body` field —
 * the body is only read by the hardened `activate_skill` tool. A
 * compile error will surface any attempt to put bodies into context.
 */
export interface SkillSummary {
  name: string;
  description: string;
  category: SkillCategory;
  trust: SkillTrust;
  score: number;
  matchedTriggers: string[];
  matchedPaths: string[];
  recencyBoost: boolean;
}

/**
 * The merged, runtime view of a skill: the manifest + the parsed
 * SKILL.md body + the resolved trust + the install path. This is what
 * SkillRegistry stores and what `activate_skill` consumes.
 */
export interface InstalledSkillRecord {
  manifest: SkillManifest;
  /** Parsed SKILL.md body (markdown after the frontmatter). */
  body: string;
  /** Path to the SKILL.md file on disk. */
  sourcePath: string;
  /** Path to the skill folder. */
  skillDir: string;
  /** Resolved trust (may differ from the on-disk declaration). */
  trust: SkillTrust;
  /** "builtin" | "user" | "project" | "extension" — the install location. */
  scope: "builtin" | "user" | "project" | "extension";
  /** When the registry first saw this skill (ms since epoch). */
  installedAt: number;
  /** sha256 of the manifest (hex). */
  manifestSha256: string;
  /** ms since epoch of the most recent successful `skill test`. */
  lastValidatedAt?: number;
  /** The owning extension id, when scope === "extension". */
  extensionId?: string;
  /** When true, `activate_skill` refuses to load the body even if
   *  trust is otherwise sufficient. Set by `skill disable <name>`. */
  disabled?: boolean;
  /** Why `skill disable` was last invoked. */
  disabledReason?: string;
}

/**
 * Per-install trust decision stored next to the manifest.
 * Lets the resolver avoid re-deriving from path on every boot.
 */
export interface SkillTrustRecord {
  skillPath: string;
  trust: SkillTrust;
  decidedAt: number;
  decidedBy: "user" | "trust-resolver" | "extension" | "auto";
  note?: string;
}

export const DEFAULT_SKILL_MEMORY_POLICY: SkillMemoryPolicy = {
  mayReadProjectMemory: true,
  mayWriteProjectMemory: true,
  mayReadUserMemory: false,
  mayWriteUserMemory: false,
};

/** Errors thrown by manifest/validator/lifecycle. */
export class SkillValidationError extends Error {
  readonly field: string;
  readonly code: string;
  constructor(field: string, code: string, message: string) {
    super(`${field}: ${message} (${code})`);
    this.name = "SkillValidationError";
    this.field = field;
    this.code = code;
  }
}

/** Lower-case, kebab-case regex enforced by validator. */
export const SKILL_NAME_REGEX = /^[a-z][a-z0-9-]{0,63}$/;

/** Loose semver regex: major.minor.patch with optional pre-release. */
export const SEMVER_REGEX = /^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/;
