/**
 * Regenerates `src/model/provider/TRANSPORTS.md` from the pinned Models.dev
 * snapshot. Run after `npm run sync:models`; CI compares the committed table
 * against a fresh run so a catalog refresh that introduces an unknown npm
 * identity fails the build instead of silently advertising unrunnable models.
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { ModelsDevCatalogService } from "../src/model/provider/models-dev-catalog.js";
import { MODELS_DEV_SNAPSHOT_METADATA } from "../src/model/provider/models-dev-snapshot.js";
import { hasTransport } from "../src/model/provider/transports.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

export interface TransportCoverageRow {
  npm: string;
  installed: boolean;
  providers: string[];
  modelCount: number;
}

/** Every npm identity the snapshot advertises, at provider or model level. */
export function transportCoverage(catalog: ModelsDevCatalogService): TransportCoverageRow[] {
  const rows = new Map<string, { providers: Set<string>; modelCount: number }>();
  const record = (npm: string, providerId: string, models: number) => {
    const row = rows.get(npm) ?? { providers: new Set<string>(), modelCount: 0 };
    row.providers.add(providerId);
    row.modelCount += models;
    rows.set(npm, row);
  };

  for (const provider of catalog.providers()) {
    const models = Object.values(provider.models);
    const overridden = models.filter((model) => model.provider?.npm);
    if (provider.npm) record(provider.npm, provider.id, models.length - overridden.length);
    for (const model of overridden) record(model.provider!.npm!, provider.id, 1);
  }

  return [...rows.entries()]
    .map(([npm, row]) => ({
      npm,
      installed: hasTransport(npm),
      providers: [...row.providers].sort(),
      modelCount: row.modelCount,
    }))
    .sort((a, b) => a.npm.localeCompare(b.npm));
}

function render(rows: TransportCoverageRow[]): string {
  const meta = MODELS_DEV_SNAPSHOT_METADATA;
  const lines = [
    "# Transport coverage",
    "",
    "Generated by `npm run sync:transports`. Do not edit by hand.",
    "",
    `Snapshot: ${meta.retrievedAt} · ${meta.providerCount} providers · ${meta.modelCount} models.`,
    "",
    "A model is runnable only when its npm identity has an installed loader in",
    "`src/model/provider/transports.ts`. Identities marked missing are parsed and",
    "listed, but their models are not offered for turns.",
    "",
    "| npm identity | loader | providers | models |",
    "|---|---|---|---|",
  ];
  for (const row of rows) {
    lines.push(
      `| \`${row.npm}\` | ${row.installed ? "installed" : "**missing**"} `
      + `| ${row.providers.length} | ${row.modelCount} |`,
    );
  }
  const missing = rows.filter((row) => !row.installed);
  lines.push("", `Coverage: ${rows.length - missing.length}/${rows.length} identities installed.`, "");
  return lines.join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const catalog = new ModelsDevCatalogService();
  const rows = transportCoverage(catalog);
  const target = path.join(ROOT, "src", "model", "provider", "TRANSPORTS.md");
  await writeFile(target, render(rows), { mode: 0o644 });
  const missing = rows.filter((row) => !row.installed);
  process.stdout.write(`transport coverage: ${rows.length - missing.length}/${rows.length} installed\n`);
  if (missing.length > 0) {
    process.stdout.write(`missing loaders: ${missing.map((row) => row.npm).join(", ")}\n`);
    process.exitCode = 1;
  }
}
